---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: default
  labels:
    app: hello
spec:
  # ClusterIP | NodePort | LoadBalancer
  type: ClusterIP 
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
      app: hello